/**
 * EZKL Proof Verifier
 *
 * Verifies ZK proofs generated by EZKL using the Python CLI
 */

import { readFile, writeFile, unlink } from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import { randomBytes } from 'crypto';
import path from 'path';
import type { EZKLProof } from '../types.js';

const execAsync = promisify(exec);

export interface EZKLVerifierConfig {
  vkPath: string;
  settingsPath: string;
  ezklPath?: string;  // Path to ezkl binary
}

export class EZKLVerifier {
  private vkPath: string;
  private settingsPath: string;
  private ezklPath: string;

  constructor(config: EZKLVerifierConfig) {
    this.vkPath = config.vkPath;
    this.settingsPath = config.settingsPath;
    this.ezklPath = config.ezklPath || '/Users/norman/.ezkl/ezkl';  // Default from our installation
  }

  /**
   * Verify an EZKL proof
   */
  async verify(proof: EZKLProof): Promise<boolean> {
    const tempProofPath = path.join('/tmp', `proof-${randomBytes(8).toString('hex')}.json`);

    try {
      // Write proof to temporary file
      await writeFile(tempProofPath, JSON.stringify(proof, null, 2));

      // Call EZKL verify command
      const command = `${this.ezklPath} verify ` +
        `-P ${tempProofPath} ` +
        `--settings-path ${this.settingsPath} ` +
        `--vk-path ${this.vkPath}`;

      console.log('Running EZKL verify command:', command);

      const { stdout, stderr } = await execAsync(command, {
        timeout: 60000  // 60 second timeout
      });

      console.log('EZKL stdout:', stdout);
      if (stderr) {
        console.log('EZKL stderr:', stderr);
      }

      // Check if verification succeeded
      // EZKL returns "verified" in output on success
      const output = stdout.toLowerCase();
      return output.includes('verified') || output.includes('proof is valid');

    } catch (error) {
      console.error('EZKL verification error:', error);
      if (error instanceof Error) {
        console.error('Error message:', error.message);
      }
      return false;
    } finally {
      // Clean up temporary file
      try {
        await unlink(tempProofPath);
      } catch {
        // Ignore cleanup errors
      }
    }
  }

  /**
   * Check if EZKL is available
   */
  async checkAvailability(): Promise<boolean> {
    try {
      const { stdout } = await execAsync(`${this.ezklPath} --version`, {
        timeout: 5000
      });
      console.log('EZKL version:', stdout.trim());
      return true;
    } catch (error) {
      console.error('EZKL not available:', error);
      return false;
    }
  }
}
