#!/usr/bin/env python3
"""
Generate IPA SRS (Structured Reference String)
Run this before generating models with IPA commitment
"""

import ezkl
import json
import sys
import asyncio

async def main():
    print("\n" + "="*70)
    print("  Generating IPA SRS for zkSalaria Models")
    print("="*70)

    # Create a minimal settings file with IPA commitment to generate SRS
    # The actual settings will be generated by each model
    # We just need to know the commitment type and approximate circuit size

    print("\n→ Creating temporary IPA settings...")
    temp_settings = {
        "run_args": {
            "input_scale": 14,
            "param_scale": 14,
            "rebase_scale": None,
            "scale_rebase_multiplier": 10,
            "lookup_range": [-32768, 32768],
            "logrows": 17,  # Circuit size (2^17 rows should be sufficient)
            "num_inner_cols": 2,
            "variables": [["batch_size", 1]],
            "input_visibility": "Private",
            "output_visibility": "Public",
            "param_visibility": "Fixed",
            "rebase_frac_zero_constants": False,
            "check_mode": "UNSAFE",
            "commitment": "IPA",
            "decomp_base": 16384,
            "decomp_legs": 2,
            "bounded_log_lookup": False,
            "ignore_range_check_inputs_outputs": False,
            "epsilon": 2.220446049250313e-16
        },
        "num_rows": 131072,
        "total_assignments": 8192,
        "total_const_size": 2048,
        "model_instance_shapes": [[1]],
        "model_output_scales": [14],
        "model_input_scales": [14],
        "module_sizes": {
            "polycommit": [],
            "poseidon": [0, [0]]
        },
        "required_lookups": [],
        "required_range_checks": [],
        "check_mode": "UNSAFE",
        "version": "22.2.4",
        "num_blinding_factors": None,
        "timestamp": 0
    }

    with open("temp_ipa_settings.json", "w") as f:
        json.dump(temp_settings, f, indent=2)
    print("✓ Temporary settings created")

    # Get IPA SRS
    print("\n→ Downloading/generating IPA SRS...")
    print("  (This may take a few minutes...)")

    try:
        # get_srs will automatically use IPA commitment based on settings file
        await ezkl.get_srs(
            settings_path="temp_ipa_settings.json",
            srs_path="ipa.srs"
        )
        print("✓ IPA SRS generated: ipa.srs")

        # Clean up temp file
        import os
        os.remove("temp_ipa_settings.json")
        print("✓ Temporary settings removed")

        print("\n" + "="*70)
        print("✅ IPA SRS ready!")
        print("="*70)
        print("\nNext steps:")
        print("  1. Run: uv run python generate_all_models.py")
        print("  2. Models will now use IPA commitment (trustless verification!)")
        print("="*70 + "\n")

        return 0

    except Exception as e:
        print(f"\n❌ Failed to generate IPA SRS: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
