#!/usr/bin/env -S npx tsx
/**
 * Test the TypeScript proof verifier with generated proofs
 */

import { readFile } from 'fs/promises';
import { join } from 'path';
import { ProofType, ProofOutput } from './types';
import { verifyIncomeProof } from './proof-verifier';

async function testProof(proofType: ProofType, modelName: string) {
  console.log(`\nTesting ${modelName}...`);

  try {
    // Load the test proof that was generated by Python
    const proofPath = join(__dirname, '..', 'generated', modelName, 'test_proof.json');
    const proofJson = await readFile(proofPath, 'utf-8');

    // Create proof output object
    const proof: ProofOutput = {
      proofType,
      proofJson,
      publicInputs: {
        result: true,
        payments: [5000, 5100, 5200, 4900, 5000, 4800],
        thresholdMin: 25000
      }
    };

    // Verify
    const result = await verifyIncomeProof(proof);

    if (result.success && result.verified) {
      console.log(`  ✅ PASSED (${result.duration}ms)`);
      return true;
    } else {
      console.log(`  ❌ FAILED: ${result.error || 'Verification failed'}`);
      return false;
    }
  } catch (error) {
    console.log(`  ❌ ERROR: ${error instanceof Error ? error.message : String(error)}`);
    return false;
  }
}

async function main() {
  console.log('='.repeat(70));
  console.log('  Testing TypeScript Proof Verifier');
  console.log('  Verifying proofs generated by Python EZKL API');
  console.log('='.repeat(70));

  const tests = [
    { type: ProofType.INCOME_ABOVE_THRESHOLD, name: 'income_above_threshold' },
    { type: ProofType.INCOME_RANGE, name: 'income_range' },
    { type: ProofType.AVERAGE_INCOME, name: 'average_income' },
    { type: ProofType.FIRST_TIME_LOAN_ELIGIBILITY, name: 'first_time_loan' }
  ];

  // Run tests sequentially to avoid file conflicts
  const results = [];
  for (const { type, name } of tests) {
    results.push(await testProof(type, name));
  }

  const passed = results.filter(r => r).length;
  const total = results.length;

  console.log('\n' + '='.repeat(70));
  if (passed === total) {
    console.log(`  ✅ ALL TESTS PASSED (${passed}/${total})`);
    console.log('='.repeat(70));
    console.log('\n  TypeScript verifier works with Python-generated proofs!');
    process.exit(0);
  } else {
    console.log(`  ⚠️  SOME TESTS FAILED (${passed}/${total})`);
    console.log('='.repeat(70));
    process.exit(1);
  }
}

main().catch(console.error);
