export const midnightFacts = [
  "Midnight Network is a blockchain designed to bring \"rational privacy\" by balancing utility and data protection.",
  "Midnight utilizes zero-knowledge proofs (ZKPs) to verify information without revealing sensitive details.",
  "Midnight is built as a privacy-focused sidechain on the Cardano blockchain.",
  "Midnight is developed by Input Output Global (IOG), the team behind Cardano, with a spinout called Shielded.",
  "Midnight's Compact programming language is based on TypeScript, offering a familiar syntax for building modular smart contracts.",
  "Midnight's programmable data protection shields wallet addresses and transaction information from unauthorized views.",
  "Midnight's selective disclosure allows users to share specific data with regulators while keeping the rest private.",
  "Midnight's compliance-focused design helps meet regulations like GDPR through data minimization principles.",
  "Midnight employs ZK-SNARKs for compact, efficient proofs that enhance privacy and scalability.",
  "Midnight's testnet includes features like hard forking and minimized chain resets for robust testing.",
  "Midnight's Glacier Drop is a multi-phase airdrop distributing the entire 24 billion NIGHT token supply.",
  "Nearly 34 million addresses across 8 blockchains (like ADA, BTC, ETH) are eligible for Midnight's NIGHT claims.",
  "Holding Midnight's NIGHT generates DUST, enabling free transactions on the Midnight network.",
  "Midnight unlocks Web3 potential for enterprises with secure, cloud-like infrastructure.",
  "Midnight overcomes the traditional blockchain trade-off between utility and privacy.",
  "Midnight's modular smart contracts in Compact provide a seamless developer experience.",
  "Midnight's ZKPs enable confidential smart contracts and payments without exposing data.",
  "Midnight supports secure, anonymous voting systems that prove eligibility without revealing identities.",
  "Midnight's ZK technology reduces verification costs, boosting blockchain scalability.",
  "Midnight enables light clients to verify transactions without downloading the entire blockchain.",
  "Midnight improves interoperability with sidechains for seamless cross-chain transactions.",
  "Midnight is positioned as a fourth-generation blockchain emphasizing data protection.",
  "Midnight pioneers \"data protection blockchains\" with granular control over confidentiality.",
  "Midnight's shielding ensures transactions occur without leaking user data or metadata.",
  "Midnight's access keys allow selective viewing of encrypted data by authorized parties.",
  "Midnight is ideal for healthcare, enabling selective sharing of medical records securely.",
  "In finance, Midnight offers controlled transparency for regulatory compliance.",
  "For balloting, Midnight provides fraud-resistant voting while preserving voter privacy.",
  "Midnight's programmable data protection lets developers embed business policies into apps.",
  "Midnight protects user, commercial, and transaction metadata comprehensively.",
  "Midnight integrates ZK-SNARKs into Zswap and Kachina protocols for secure transactions.",
  "Midnight's ZK-STARKs offer transparency without trusted setups, though SNARKs are preferred for efficiency.",
  "Midnight's community input drives improvements to testnet scalability and performance.",
  "Midnight Insights features podcasts on the network's origins and block producer experiences.",
  "Midnight's cooperative tokenomics support multi-chain access and participation.",
  "Shielded, a key engineering spinout for Midnight, specializes in privacy-enhancing decentralized tech.",
  "The Midnight Foundation advances global adoption and community support.",
  "Midnight addresses key barriers for organizations adopting blockchain technology.",
  "Midnight enables radical new business models focused on privacy and data ownership.",
  "Midnight's ZK technology relies on advanced cryptography, not \"magic,\" for verification.",
  "In Midnight's ZK, a prover demonstrates truth to a verifier without sharing underlying info.",
  "Midnight's ZK-SNARKs use elliptic curve pairings and algebraic techniques for compact proofs.",
  "Midnight supports data aggregation for blockchain oracles, improving efficiency.",
  "Midnight's NIGHT token powers the network with built-in privacy features.",
  "Midnight's recent updates include new open-source DApps and Compact contracts.",
  "Midnight has a growing ecosystem through strategic partnerships.",
  "Midnight offers updated guides available for aspiring block producers.",
  "Midnight's dev diaries explore topics like hashing, digital signatures, and Web3 basics.",
  "Midnight's tutorials guide developers in creating DApps on the devnet.",
  "Midnight focuses on real-world compliance while maintaining verifiability and privacy."
];